create table if not exists customers
(
    id           int primary key generated by default as identity,
    name         varchar(255)        not null,
    email        varchar(255) unique not null,
    phone_number varchar(255),
    website      varchar(255),
    inn          int not null,
    description  varchar(15000),
    type         varchar(255)not null,
    country      varchar(255)not null,
    city         varchar(255)not null,
    address      varchar(255)not null,
    creation_date     timestamp default now(),
    update_date       timestamp default now()
);