create table if not exists product
(
    id           int primary key generated by default as identity,
    name         varchar(255)  not null,
    vendor_code  varchar(255)  not null,
    count        int,
    price        double precision,
    guarantee    varchar       not null,
    available    boolean       not null,
    description  varchar(15000) not null,
    type         varchar(255)  not null,
    receipt_date date
);