create table if not exists customers
(
    id           int primary key generated by default as identity,
    name         varchar(255)        not null,
    email        varchar(255) unique not null,
    phone_number varchar(255)        not null,
    website      varchar(255),
    inn          bigint unique       not null,
    description  varchar(15000),
    type         varchar(255)        not null,
    country      varchar(255)        not null,
    city         varchar(255)        not null,
    address      varchar(255)        not null
);